### ISSUE TITLE
MobileNet-V1: Verification step stitched_ip_rtlsim throws an error

### ISSUE THREAD

**Issue by hannahxy13** [Xilinx/finn#1113] opened 2024-06-26 10:26 UTC
## Quick summary
When running the build flow for MobileNet-V1 from FINN-examples, when the verification step "stitched_ip_rtlsim" is run, which happens at "step_create_stitched_ip", an error is thrown.

## Details
The verification step "stitched_ip_rtlsim" was added to the build flow for MobileNet-V1, from the FINN-examples repository. When the build is run using Docker, once "step_create_stitched_ip" is reached, the following error is thrown:
```
return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(int64))
```
It seems that the verification datatype is float, but is expected to be int64.

Looking at the intermediate ONNX models, it seems the issue is occurring in the LabelSelect node at the end of the model. Attached are screenshots from Netron showing the properties of the output tensor of the LabelSelect node for the different steps in the build flow:
- step_hw_ipgen.onnx
![image](https://github.com/Xilinx/finn/assets/128490865/83de6209-1fce-4572-85a0-b5a101bc1b4b)

- step_set_fifo_depths.onnx
![image](https://github.com/Xilinx/finn/assets/128490865/802866ba-8c37-4fe5-877f-6157174c50a9)

- verify_step_stitched_rtlsim.onnx
![image](https://github.com/Xilinx/finn/assets/128490865/db4dfc69-b995-4a57-b42e-13fa11f988bb)

It can be seen that at "step_hw_ipgen", the datatype is int64. The step right after it, "step_set_fifo_depths", appears to change the datatype to float32, and this change persists in the following step "step_create_stitched_ip", which causes the verification step "stitched_ip_rtlsim" to fail.

ONNX files:
[mobilenetv1_onnx_files.zip](https://github.com/user-attachments/files/15986415/mobilenetv1_onnx_files.zip)

### Steps to Reproduce

1. Clone the FINN repository
2. Checkout the dev branch, with commit hash: [25c1c99]
3. Set the environment variable FINN_ROOT as the FINN repository that was cloned
4. Clone the FINN-examples repository
5. Add the verification step "stitched_ip_rtlsim" to the build.py file for the MobileNet-V1 model build configuration
6. Download the MobileNet-V1 ONNX model using the script in the models folder
7. Update the MobileNet-V1 ONNX model to use version 11 ops
8. Navigate to the build folder for MobileNet-V1 and start the docker container with the command:
`$FINN_ROOT/run-docker.sh build_custom . build`
9. Allow the build to run, and once it reaches "step_create_stitched_ip" it will throw an error

### Expected behavior
The verification step was expected to complete and generate a verification output file, without throwing an error.

### Actual behavior
The verification step throws an error, which then causes the build to fail and not generate a verification output file.

**Comment by auphelia** [comment] 2024-09-19 14:40
The issue is resolved by the merge of this PR: https://github.com/Xilinx/finn/pull/1192

**Closed by auphelia** 2024-09-19 14:40 UTC
Labels: bug
